version: "2"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - "./html:/var/www/html"
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "db-data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db-data:

